[package]
org = "ballerina"
name = "io"
version = "0.6.0-alpha9"

[[platform.java11.dependency]]
path = "../io-native/build/libs/io-native-0.6.0-alpha9-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "io"
version = "0.6.0-alpha9-SNAPSHOT"


[[platform.java11.dependency]]
path = "../io-test-utils/build/libs/io-test-utils-0.6.0-alpha9-SNAPSHOT.jar"
groupId = "org.ballerinalang.stdlib.io"
scope = "testOnly"
artifactId = "io"
version = "0.6.0-alpha9-SNAPSHOT"
